"""Views, one for each PastForward page."""
from PastForward.views.landing import show_landing
from PastForward.views.index import show_index
from PastForward.views.users import show_user
from PastForward.views.auth import show_auth
from PastForward.views.create import show_create
from PastForward.views.delete import show_delete
from PastForward.views.edit import show_edit
from PastForward.views.explore import show_explore
from PastForward.views.followers import show_followers
from PastForward.views.following import show_following
from PastForward.views.login import show_login
from PastForward.views.logout import show_logout
from PastForward.views.password import show_password
from PastForward.views.posts import show_posts
from PastForward.views.images import uploaded_file
from PastForward.views.likes import handle_likes
from PastForward.views.comments import handle_comments
from PastForward.views.changeposts import handle_posts
from PastForward.views.auth import show_auth
from PastForward.views.follows import handle_follows
from PastForward.views.accounts import show_accounts
from PastForward.views.newpost import show_newpost
